project:
  type: default

format:
  html:
    css: assets/style.css
    filters:
      - assets/legal-numbering.lua
    embed-resources: true
    format-links: false
    number-sections: false
    crossrefs-hover: false
    theme: none
    minimal: true
    toc-title: "TABLE OF CONTENTS"

crossref:
  sec-prefix: ""
  chapters: false
